adding nginx-wsgi-flask docker-compose sample
docker/awesome-compose pull request #101
Opened 2021-03-14 19:07 UTC by GrantBirki

2021-03-14 19:28 UTC, GrantBirki commented
All commits to this pull request are complete. It is ready to be peer reviewed and merged! @glours  @alobbs  🚀

2021-03-19 09:57 UTC, aiordache requested changes
Thank you for taking the time to prepare this!

2021-03-19 09:57 UTC, aiordache commented on nginx-wsgi-flask/Makefile
> +make build:
I think this Makefile can be removed, it is not necessary.

2021-03-19 09:57 UTC, aiordache commented on vuejs/vuejs/yarn.lock
> +"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":
unrelated change

2021-03-19 09:57 UTC, aiordache commented on nginx-wsgi-flask/README.md
> +## Build with Makefile (easy)
This can be removed, no need to rely on make for build.

2021-03-19 09:57 UTC, aiordache commented on nginx-wsgi-flask/docker-compose.yaml
> +    links:
`links` field can be removed. By default the two services are placed in the same network so they can reach each other.

2021-03-19 15:04 UTC, GrantBirki commented
@aiordache, I have made all the edits you have suggested, thank you! Let me know if there is anything else.

2021-03-20 21:09 UTC, GoToCoding commented on nginx-wsgi-flask/nginx/Dockerfile
> +# # Uncomment to keep the nginx logs inside the container - Leave out to to log to stdout and stderr
typo in `Leave out to to log`

2021-03-20 21:13 UTC, GoToCoding commented on nginx-wsgi-flask/README.md
> +├── Makefile
And don't forget to delete this )

2021-03-21 05:14 UTC, GrantBirki commented
Closing this pull request and tracking the new one [here](https://github.com/docker/awesome-compose/pull/112). I am opening a new one to include the new `yarn.lock` changes as seen above. Looking for an approval on that PR. Thanks!

2021-03-21 05:14 UTC, closed without merging