Compliance to awesome repository requirements
docker/awesome-compose pull request #38
Opened 2020-03-26 17:12 UTC by glours

Add
 - CODEOWNERS
 - MAINTAINERS
 - CONTRIBUTING.md

Fix `README.md` to be compliant with [awesome repository](https://github.com/sindresorhus/awesome#readme)

Signed-off-by: Guillaume Lours <guillaume.lours@docker.com>

2020-03-26 17:42 UTC, chris-crone requested changes
Couple of minor changes, thanks @glours!

2020-03-26 17:42 UTC, chris-crone commented on CONTRIBUTING.md
> +You can request a new example of application by submitting an issue to our GitHub Repository.
nit: missing `\n` after heading

2020-03-26 17:42 UTC, chris-crone commented on CONTRIBUTING.md
> +You can request a new example of application by submitting an issue to our GitHub Repository.
```suggestion

You can request a new example of an application by submitting an issue to our GitHub repository.  
```

2020-03-26 17:42 UTC, chris-crone commented on CONTRIBUTING.md
> +If you would like to implement a new application sample, please submit an issue with a proposal first,
```suggestion
If you would like to submit a new application example, please start by submitting a proposal as an issue.
```

2020-03-26 17:42 UTC, chris-crone commented on CONTRIBUTING.md
> +Then we'll consult the community to know what can be the most valuable application with this technology/language/framework...
```suggestion
The maintainers will then use this issue to discuss what the the most valuable example for the application, technology, language, or framework would be.
```

2020-03-26 17:42 UTC, chris-crone commented on CONTRIBUTING.md
> +After the choice made, you can submit your pull request following the choice of the community without forgetting to add :
```suggestion
After the choice has been made, you can submit your a pull request not forgetting to:
```

2020-03-26 17:42 UTC, chris-crone commented on CONTRIBUTING.md
> +- a local README.md to describe the application and explain how to run/use the sample.
```suggestion
- include an example README.md to describe the application and explain how to run/use the sample
```

2020-03-26 17:42 UTC, chris-crone commented on CONTRIBUTING.md
> +## Missing a kind of application?
```suggestion
## Missing an example?
```

2020-03-26 17:42 UTC, chris-crone commented on CONTRIBUTING.md
> +## Update a existing sample
We can actually remove this

2020-03-26 17:42 UTC, chris-crone commented on CONTRIBUTING.md
> +Before submitting a new application, check if there isn't already application sample matching your need.
We should move this (and the next line) up to the other section

2020-03-26 17:42 UTC, chris-crone commented on CONTRIBUTING.md
> +aligned and increase the chance that the change is accepted.
I think you can remove this as it's more targeted at code/specs

2020-03-27 10:34 UTC, chris-crone requested changes
Minor changes after seeing it all together. Thanks @glours!

2020-03-27 10:34 UTC, chris-crone commented on CONTRIBUTING.md
> +If there is one, consider to update it instead of create a new one.
nit:
```suggestion
If there is one, consider updating it instead of creating a new one.
```

2020-03-27 10:34 UTC, chris-crone commented on CONTRIBUTING.md
> +After the choice has been made, you can submit your a pull request not forgetting to:
```suggestion
After the choice has been made, you can submit a pull request with the example remembering to:
```

2020-03-27 10:40 UTC, chris-crone approved these changes
LGTM

2020-03-27 10:41 UTC, merged

2026-08-31 13:50 UTC, mandervrik reviewed
N