Django example
docker/awesome-compose pull request #43
Opened 2020-04-06 19:42 UTC by lfvilella

Adding simple [Django](https://www.djangoproject.com/) example.

2020-04-07 08:04 UTC, glours requested changes
Thanks @lfvilella for your contribution.
Can you also update the main [README.md](https://github.com/docker/awesome-compose/blob/master/README.md) to add your sample in the Single service samples section please?

2020-04-07 08:04 UTC, glours commented on django/docker-compose.yml
> +version: '3'
Can you be more specific on the version and use `3.7`

2020-04-07 12:00 UTC, glours approved these changes
LGTM

2020-04-07 12:00 UTC, merged

2020-04-07 12:01 UTC, glours commented
@lfvilella Thank you very much for the pull request 🙏

2026-08-31 13:46 UTC, mandervrik reviewed
Sorry for the late